/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bitcamp.myproject;

import java.util.Scanner;

public class App {
    
  public static void main(String[] args) {
    
    Scanner keyboard = new Scanner(System.in);
    
    System.out.println("아이디를 입력하세요:");
    String id = keyboard.nextLine();
    
    
    System.out.println("비밀번호를 입력하세요 : ");
    String passward = keyboard.nextLine();
    
    System.out.println();
    
    System.out.printf("로그인되었습니다.\n");
    System.out.printf("안녕하세요  %s 님", id);
    
    
    
    keyboard.close();
  }
}





    
    
