/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.eomcs.lms;

import java.util.Scanner;
        
public class App {

  public static void main(String[] args) {
    //키보드에서 사용자가 입력한 값을 읽어 문자열이나 정수, 부동소수점 등으로 리턴하는역할
    Scanner keyboard = new  Scanner(System.in);
    
        
    System.out.println("스케쥴 관리 프로그램입니다");
    System.out.println("아이디를 입력하세요 : "); 
    System.out.println("비밀번호를 입력하세요 : ");

  }
}
