/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bitcamp.myproject;

public class App {

  public static void main(String[] args) {
    System.out.println("스케쥴 관리 프로그램입니다");
    System.out.println("아이디를 입력하세요 : "); 
    System.out.println("비밀번호를 입력하세요 : ");

  }
}
